# Generated by Django 5.2.1 on 2025-06-25 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('is_main_facility', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='from_location',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='to_location',
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='from_bin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_bin', to='inventory.bin'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='to_bin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_bin', to='inventory.bin'),
        ),
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='listing_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bin',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.source'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
