# Generated by Django 5.2.1 on 2025-06-27 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorymovement',
            old_name='user',
            new_name='performed_by',
        ),
    ]
