# Generated by Django 5.2 on 2025-05-07 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorymovement',
            name='from_location',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='to_location',
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='from_bin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_bin', to='inventory.bin'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='to_bin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_bin', to='inventory.bin'),
        ),
    ]
