# Generated by Django 5.2.1 on 2025-06-26 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_source_remove_inventorymovement_from_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorymovement',
            name='performed_by',
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='from_bin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_from', to='inventory.bin'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('RECEIVE', 'Received'), ('TRANSFER', 'Transferred'), ('PICK', 'Picked for Order'), ('RETURN', 'Returned')], max_length=10),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='to_bin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_to', to='inventory.bin'),
        ),
        migrations.AlterField(
            model_name='item',
            name='bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.bin'),
        ),
    ]
