# Generated by Django 5.2.1 on 2026-01-07 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_user_inventorymovement_performed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='bin',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bin',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='inventory.source'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='from_bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_out', to='inventory.bin'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('RECEIVE', 'Received'), ('TRANSFER', 'Transferred'), ('PICK', 'Picked for Order'), ('RETURN', 'Returned'), ('ADJUST', 'Adjusted')], max_length=10),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='to_bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_in', to='inventory.bin'),
        ),
        migrations.AlterField(
            model_name='item',
            name='source',
            field=models.CharField(choices=[('eBay', 'eBay'), ('Manual', 'Manual'), ('Other', 'Other')], default='eBay', max_length=100),
        ),
        migrations.AddIndex(
            model_name='bin',
            index=models.Index(fields=['location', 'code'], name='inventory_b_locatio_03949f_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['item', '-timestamp'], name='inventory_i_item_id_1c5f80_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['movement_type', '-timestamp'], name='inventory_i_movemen_c634ad_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['sku'], name='inventory_i_sku_3e99d5_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['source'], name='inventory_i_source_d68b23_idx'),
        ),
        migrations.AddField(
            model_name='inventorybalance',
            name='bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='inventory.bin'),
        ),
        migrations.AddField(
            model_name='inventorybalance',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='inventory.item'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['item', 'bin'], name='inventory_i_item_id_105481_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['bin'], name='inventory_i_bin_id_e4c78a_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.UniqueConstraint(fields=('item', 'bin'), name='uniq_item_bin_balance'),
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='balance_qty_nonnegative'),
        ),
    ]
