# Generated by Django 5.2.1 on 2025-06-26 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventorymovement_performed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='source',
            field=models.CharField(default='eBay', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='from_bin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_out', to='inventory.bin'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='to_bin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_in', to='inventory.bin'),
        ),
    ]
