# Generated by Django 5.2.1 on 2026-01-09 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorybalance_remove_item_bin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_items', to='inventory.bin'),
        ),
    ]
