# Generated by Django 5.2.1 on 2025-06-26 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_source_alter_inventorymovement_from_bin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bin',
            options={'ordering': ['location__name', 'code']},
        ),
        migrations.AlterModelOptions(
            name='inventorymovement',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['sku']},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['name']},
        ),
    ]
