# Generated by Django 5.2.1 on 2025-05-28 17:24

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_item_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
