# Generated by Django 5.2.1 on 2025-05-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20250528_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='listing_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
